// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: app.proto

package appRouter

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// AppRouterService defines service.
type AppRouterService interface {
	ById(ctx context.Context, req *ByIdRequest) (*ByIdResponse, error)
}

func AppRouterService_ById_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &ByIdRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(AppRouterService).ById(ctx, reqbody.(*ByIdRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// AppRouterServer_ServiceDesc descriptor for server.RegisterService.
var AppRouterServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "appRouter.AppRouter",
	HandlerType: ((*AppRouterService)(nil)),
	Methods: []server.Method{
		{
			Name: "/appRouter.AppRouter/ById",
			Func: AppRouterService_ById_Handler,
		},
	},
}

// RegisterAppRouterService registers service.
func RegisterAppRouterService(s server.Service, svr AppRouterService) {
	if err := s.Register(&AppRouterServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("AppRouter register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedAppRouter struct{}

func (s *UnimplementedAppRouter) ById(ctx context.Context, req *ByIdRequest) (*ByIdResponse, error) {
	return nil, errors.New("rpc ById of service AppRouter is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// AppRouterClientProxy defines service client proxy
type AppRouterClientProxy interface {
	ById(ctx context.Context, req *ByIdRequest, opts ...client.Option) (rsp *ByIdResponse, err error)
}

type AppRouterClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewAppRouterClientProxy = func(opts ...client.Option) AppRouterClientProxy {
	return &AppRouterClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *AppRouterClientProxyImpl) ById(ctx context.Context, req *ByIdRequest, opts ...client.Option) (*ByIdResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/appRouter.AppRouter/ById")
	msg.WithCalleeServiceName(AppRouterServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("AppRouter")
	msg.WithCalleeMethod("ById")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &ByIdResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
